site_name: SLAF Documentation
site_description: Sparse Lazy Array Format - High-performance single-cell data storage and analysis
site_author: Pavan Ramkumar
site_url: https://slaf-project.github.io/slaf/

# Repository
repo_name: slaf-project/slaf
repo_url: https://github.com/slaf-project/slaf
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Pavan Ramkumar

# Theme
theme:
  name: material
  # logo: assets/logo.svg
  # favicon: assets/favicon.png

  # Color palette
  palette:
    # Light mode (default)
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  # Features
  features:
    - navigation.sections
    - content.code.copy

  # Social
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/slaf-project/slaf

# Plugins
plugins:
  - search
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors:
      show_email_address: false
  - minify:
      minify_html: true
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [slaf]
          options:
            # Core display options
            show_source: true
            show_root_heading: true
            show_signature_annotations: true
            show_category_heading: true
            heading_level: 2
            show_if_no_docstring: false
            members_order: source
            show_bases: true
            show_root_toc_entry: true
            docstring_style: google

            # Enhanced rendering for better examples
            show_examples: true

            # Visual separation and organization
            show_signature_annotations: true
            show_source: true
            show_root_heading: true
            show_category_heading: true
            heading_level: 2
            show_if_no_docstring: false
            members_order: source
            show_bases: true
            show_root_toc_entry: true

            # Filter out dunder methods except __init__
            filters: ["!^_", "!^__", "__init__"]

            # Group methods by type for better organization
            members_order: ["source", "alphabetical"]
  - awesome-pages
  - section-index

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/theme-reset.js
  - javascripts/copy-enhancement.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation
nav:
  - Home: index.md
  - Quick Start: getting-started/quickstart.md
  - User Guide:
      - How SLAF Works: user-guide/how-slaf-works.md
      - Migrating to SLAF: user-guide/migrating-to-slaf.md
  - Examples:
      - Getting Started: examples/getting-started.md
      - Lazy Processing: examples/lazy-processing.md
      - ML Training: examples/ml-training.md
      - SQL Queries: examples/sql-queries.md
  - Benchmarks: benchmarks/performance.md
  - API Reference:
      - Core: api/core.md
      - Data: api/data.md
      - Integrations: api/integrations.md
      - ML: api/ml.md
  - Development:
      - For Contributors: development/contributing.md
      - For Maintainers: development/maintaining.md
      - Benchmarks: development/benchmarks.md
  - Blog:
      - Introducing SLAF: blog/introducing-slaf.md

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/slaf-project/slaf
  generator: false

# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn
