name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Check code formatting
        run: |
          uv run ruff format --check .

      - name: Lint with ruff
        run: |
          uv run ruff check .

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Type check with mypy
        run: |
          uv run mypy slaf/ --explicit-package-bases --ignore-missing-imports

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          uv sync --extra dev --extra test

      - name: Run tests with coverage
        id: coverage
        run: |
          uv run pytest tests \
            --cov=slaf \
            --cov-report=json \
            --cov-report=term-missing \
            --cov-fail-under=60 \
            -v
          echo "coverage=$(uv run coverage report --format=total)" >> $GITHUB_OUTPUT

      - name: Parse coverage from JSON
        id: parse_coverage
        run: |
          COVERAGE_PERCENT=$(python -c "
          import json
          with open('coverage.json', 'r') as f:
              data = json.load(f)
          print(f'{data[\"totals\"][\"percent_covered\"]:.1f}')
          ")
          echo "coverage_percent=$COVERAGE_PERCENT" >> $GITHUB_OUTPUT

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: coverage.json

      - name: Output coverage percentage
        run: |
          COVERAGE_PERCENT=${{ steps.parse_coverage.outputs.coverage_percent }}
          echo "Coverage: $COVERAGE_PERCENT%"
          echo "Update the README badge manually with this percentage"
          echo "Current badge URL: https://img.shields.io/badge/coverage-${COVERAGE_PERCENT}%25-brightgreen.svg"

  dependencies:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Check for dependency conflicts
        run: |
          uv tree

      - name: Check for outdated dependencies
        run: |
          uv lock --check

  security:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Install security tools
        run: |
          uv add bandit safety

      - name: Run security checks
        run: |
          uv run bandit -r slaf/ -f json -o bandit-report.json || true
          uv run safety check --json --output safety-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            .uv/cache
            .uv/venv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-

      - name: Install build dependencies
        run: |
          uv add build wheel

      - name: Build package
        run: |
          uv run python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-py${{ matrix.python-version }}
          path: dist/

  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [lint, test, type-check, dependencies, security, build]
    if: always()
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ needs.lint.result }}" != "success" ]] || \
             [[ "${{ needs.test.result }}" != "success" ]] || \
             [[ "${{ needs.type-check.result }}" != "success" ]] || \
             [[ "${{ needs.dependencies.result }}" != "success" ]] || \
             [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ One or more required jobs failed"
            exit 1
          fi
          echo "✅ All quality checks passed"
